name: Build docker 

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  build-be:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and push frontend image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./api/
          repository: mitto98/shiny-pudding-api
          tag_with_ref: true

  build-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and push frontend image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./frontend/
          repository: mitto98/shiny-pudding
          tag_with_ref: true
